#!/usr/bin/env python3
"""
generate_mvs.py — Generate RisingWave init.sql from Solace Event Portal catalog.

Reads event metadata from the "Fleet Operations" application domain in
Solace Event Portal and writes a complete config/risingwave/init.sql that
mirrors each published event version as a RisingWave materialized view.

Usage:
  python3 generate_mvs.py [--domain "Fleet Operations"] [--dry-run]

Requires:
  SOLACE_CLOUD_TOKEN in .env at project root (or already in environment).
"""

import argparse
import json
import os
import re
import sys
import urllib.request
import urllib.parse
from pathlib import Path

# ─── Constants ────────────────────────────────────────────────────────────────

EP_BASE = "https://api.solace.cloud/api/v2/architecture"

# All columns available in routing MVs — the universe of valid SELECT targets
# (order matches the routing MV declarations in STATIC_BRANCH_MVS below)
SOURCE_COLUMNS_ORDERED = [
    "vehicle_id",
    "speed", "fuel_level", "engine_temp", "tire_pressure", "battery_voltage",
    "latitude", "longitude", "recorded_at",
    "event_type", "severity", "description", "payload", "occurred_at",
    "command_type", "parameters", "issued_at", "issued_by",
    "solace_topic",
]
SOURCE_COLUMNS = set(SOURCE_COLUMNS_ORDERED)

SCRIPT_DIR = Path(__file__).parent.resolve()

# ─── Static registry mappings ─────────────────────────────────────────────────
# Entries for hand-crafted analytics MVs in STATIC_ANALYTICS_MVS.
# EP-generated MV entries are appended at runtime by main().

STATIC_REGISTRY_MAPPINGS = [
    {
        "pattern": "fleet/telemetry/*/metrics",
        "mv": "fleet_telemetry_raw",
        "time_column": "recorded_at",
        "aggregates": {"window_5min": "vehicle_speed_5min_avg"},
    },
    {
        "pattern": "fleet/events/*/alerts/high",
        "mv": "high_severity_alerts",
        "time_column": "occurred_at",
        "enriched": "alerts_with_context",
    },
    {
        "pattern": "fleet/events/*/alerts/medium",
        "mv": "medium_severity_alerts",
        "time_column": "occurred_at",
    },
    {
        "pattern": "fleet/events/*/alerts/low",
        "mv": "low_severity_alerts",
        "time_column": "occurred_at",
    },
    {
        "pattern": "fleet/events/*",
        "mv": "fleet_events_raw",
        "time_column": "occurred_at",
    },
    {
        "pattern": "fleet/commands/*",
        "mv": "fleet_commands_raw",
        "time_column": "issued_at",
    },
]


def _infer_time_column(like_pattern: str) -> str:
    """Infer the timestamp column name from a topic LIKE pattern."""
    if "telemetry" in like_pattern:
        return "recorded_at"
    if "events" in like_pattern:
        return "occurred_at"
    if "commands" in like_pattern:
        return "issued_at"
    return "recorded_at"


def write_registry(path: Path, mappings: list) -> None:
    """Write config/topic-mv-registry.yaml — no PyYAML dependency needed."""
    lines = [
        "# =========================================================================",
        "# topic-mv-registry.yaml — Topic Pattern → RisingWave MV Mapping",
        "# AUTO-GENERATED by generate_mvs.py — DO NOT EDIT BY HAND",
        "# Re-generate: python3 generate_mvs.py",
        "# =========================================================================",
        'version: "1.0"',
        "",
        "risingwave:",
        '  host: "${RW_HOST:-localhost}"',
        '  port: "${RW_PORT:-4566}"',
        "  database: dev",
        "  user: root",
        "",
        "solace:",
        '  smf_host: "${SOLACE_HOST:-tcp://localhost:55554}"',
        '  vpn: "${SOLACE_VPN:-streaming-poc}"',
        '  username: "${SOLACE_USER:-streaming-user}"',
        '  password: "${SOLACE_PASSWORD:-default}"',
        "",
        "mappings:",
    ]
    for m in mappings:
        lines.append(f'  - pattern: "{m["pattern"]}"')
        lines.append(f'    mv: {m["mv"]}')
        if m.get("time_column"):
            lines.append(f'    time_column: {m["time_column"]}')
        if m.get("aggregates"):
            lines.append("    aggregates:")
            for k, v in m["aggregates"].items():
                lines.append(f"      {k}: {v}")
        if m.get("enriched"):
            lines.append(f"    enriched: {m['enriched']}")
        if m.get("spatial"):
            lines.append("    spatial:")
            for k, v in m["spatial"].items():
                lines.append(f"      {k}: {v}")
    lines.append("")
    path.write_text("\n".join(lines))

# ─── .env loader ──────────────────────────────────────────────────────────────

def load_env(env_path: Path) -> None:
    """Parse KEY=value lines from env_path into os.environ (skip if already set)."""
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val


# ─── EP REST helpers ──────────────────────────────────────────────────────────

def ep_get(token: str, path: str, params: dict | None = None) -> dict:
    """GET from EP API; raises on HTTP error."""
    url = EP_BASE + path
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
    })
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def get_all_pages(token: str, path: str, params: dict | None = None) -> list:
    """Paginate through all results for a list endpoint."""
    results = []
    page = 1
    while True:
        p = dict(params or {})
        p["pageSize"] = 100
        p["pageNumber"] = page
        resp = ep_get(token, path, p)
        batch = resp.get("data", [])
        results.extend(batch)
        meta = resp.get("meta", {}).get("pagination", {})
        if page >= meta.get("totalPages", 1):
            break
        page += 1
    return results


def get_domain_id(token: str, domain_name: str) -> str:
    resp = ep_get(token, "/applicationDomains", {"name": domain_name, "pageSize": 5})
    data = resp.get("data", [])
    if not data:
        raise SystemExit(f"ERROR: No application domain found named '{domain_name}'")
    return data[0]["id"]


# ─── Conversion helpers ───────────────────────────────────────────────────────

def address_levels_to_like(levels: list[dict]) -> str:
    """Convert EP deliveryDescriptor address levels to a SQL LIKE pattern."""
    parts = []
    for lvl in levels:
        if lvl.get("addressLevelType") == "literal":
            parts.append(lvl["name"])
        else:
            parts.append("%")
    return "/".join(parts)


def schema_columns(schema_content_str: str) -> list[str]:
    """
    Return the subset of SOURCE_COLUMNS that appear as top-level properties
    in the JSON Schema, preserving the canonical column order.
    """
    try:
        schema = json.loads(schema_content_str)
    except (json.JSONDecodeError, TypeError):
        return ["vehicle_id", "solace_topic"]
    props = set(schema.get("properties", {}).keys())
    return [c for c in SOURCE_COLUMNS_ORDERED if c in props & SOURCE_COLUMNS]


def mv_name(event_name: str) -> str:
    """Convert event name to a valid SQL identifier (hyphens/spaces → underscores)."""
    return re.sub(r"[^a-z0-9_]", "_", event_name.lower())


# ─── Static SQL blocks ────────────────────────────────────────────────────────

STATIC_HEADER = """\
-- =============================================================================
-- RisingWave Streaming SQL — Fleet Monitoring POC
-- AUTO-GENERATED by generate_mvs.py — DO NOT EDIT BY HAND
-- Re-generate: python3 generate_mvs.py
-- =============================================================================
-- Architecture:
--   RisingWave connects directly to Solace Platform queues via the native
--   Solace source connector (SMF protocol).  Three SOURCEs bind to separate
--   queues — one per message schema — to prevent head-of-line blocking and
--   avoid mixed-schema union columns.
--
--   Metadata columns from the Solace message envelope:
--     _rw_solace_destination  — Solace destination topic (VARCHAR)
--     _rw_solace_timestamp    — sender timestamp (TIMESTAMPTZ)
--
--   fleet_ingest_telemetry (Solace SOURCE — rw-ingest queue)
--     └─ fleet_telemetry_raw  (MV — typed columns from telemetry schema)
--   fleet_ingest_events (Solace SOURCE — events-ingest queue)
--     └─ fleet_events_raw     (MV — typed columns from events schema)
--   fleet_ingest_commands (Solace SOURCE — commands-ingest queue)
--     └─ fleet_commands_raw   (MV — typed columns from commands schema)
-- =============================================================================""".rstrip()

STATIC_SOURCE = """\
-- ── Solace source connectors — direct queue binding via SMF ──────────────────
-- Three SOURCEs bind to separate Solace queues — one per message schema.
-- Each SOURCE uses typed columns that match the flat JSON payload published
-- to that queue.  No JSONB extraction needed in routing MVs.
-- Metadata columns capture the Solace destination topic and sender timestamp
-- directly from the message envelope — no proxy or webhook required.

CREATE SOURCE fleet_ingest_telemetry (
    vehicle_id      VARCHAR,
    speed           DOUBLE PRECISION,
    fuel_level      DOUBLE PRECISION,
    engine_temp     DOUBLE PRECISION,
    tire_pressure   DOUBLE PRECISION,
    battery_voltage DOUBLE PRECISION,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION
)
INCLUDE destination AS _rw_solace_destination
INCLUDE timestamp   AS _rw_solace_timestamp
WITH (
    connector            = 'solace',
    "solace.url"         = 'tcp://solace:55555',
    "solace.queue"       = 'rw-ingest',
    "solace.vpn_name"    = 'streaming-poc',
    "solace.username"    = 'streaming-user',
    "solace.password"    = 'default',
    "solace.ack_mode"    = 'checkpoint'
)
FORMAT PLAIN ENCODE JSON;

CREATE SOURCE fleet_ingest_events (
    vehicle_id  VARCHAR,
    event_type  VARCHAR,
    severity    VARCHAR,
    description VARCHAR,
    payload     JSONB
)
INCLUDE destination AS _rw_solace_destination
INCLUDE timestamp   AS _rw_solace_timestamp
WITH (
    connector            = 'solace',
    "solace.url"         = 'tcp://solace:55555',
    "solace.queue"       = 'events-ingest',
    "solace.vpn_name"    = 'streaming-poc',
    "solace.username"    = 'streaming-user',
    "solace.password"    = 'default',
    "solace.ack_mode"    = 'checkpoint'
)
FORMAT PLAIN ENCODE JSON;

CREATE SOURCE fleet_ingest_commands (
    vehicle_id   VARCHAR,
    command_type VARCHAR,
    parameters   JSONB,
    issued_by    VARCHAR
)
INCLUDE destination AS _rw_solace_destination
INCLUDE timestamp   AS _rw_solace_timestamp
WITH (
    connector            = 'solace',
    "solace.url"         = 'tcp://solace:55555',
    "solace.queue"       = 'commands-ingest',
    "solace.vpn_name"    = 'streaming-poc',
    "solace.username"    = 'streaming-user',
    "solace.password"    = 'default',
    "solace.ack_mode"    = 'checkpoint'
)
FORMAT PLAIN ENCODE JSON;""".rstrip()

STATIC_BRANCH_MVS = """\
-- ── Routing views — alias metadata columns for downstream compatibility ───────
-- Each SOURCE has typed columns matching its queue's flat JSON schema.
-- These MVs add human-readable column aliases for the metadata fields:
--   _rw_solace_destination  → solace_topic
--   _rw_solace_timestamp    → recorded_at / occurred_at / issued_at
-- No JSONB extraction needed — all payload fields are already typed in SOURCE.

CREATE MATERIALIZED VIEW fleet_telemetry_raw AS
SELECT
    vehicle_id,
    speed,
    fuel_level,
    engine_temp,
    tire_pressure,
    battery_voltage,
    latitude,
    longitude,
    _rw_solace_timestamp   AS recorded_at,
    _rw_solace_destination AS solace_topic
FROM   fleet_ingest_telemetry;

CREATE MATERIALIZED VIEW fleet_events_raw AS
SELECT
    vehicle_id,
    event_type,
    severity,
    description,
    payload,
    _rw_solace_timestamp   AS occurred_at,
    _rw_solace_destination AS solace_topic
FROM   fleet_ingest_events;

CREATE MATERIALIZED VIEW fleet_commands_raw AS
SELECT
    vehicle_id,
    command_type,
    parameters,
    _rw_solace_timestamp   AS issued_at,
    issued_by,
    _rw_solace_destination AS solace_topic
FROM   fleet_ingest_commands;""".rstrip()

STATIC_ANALYTICS_MVS = """\
-- =============================================================================
-- ANALYTICS MATERIALIZED VIEWS — "Virtual Topics"
-- =============================================================================

-- ─── 1. High-severity alerts ─────────────────────────────────────────────────
CREATE MATERIALIZED VIEW high_severity_alerts AS
SELECT vehicle_id, event_type, description, payload, occurred_at, solace_topic
FROM   fleet_events_raw
WHERE  severity = 'high';

-- ─── 2. Alert severity tiers ─────────────────────────────────────────────────
CREATE MATERIALIZED VIEW medium_severity_alerts AS
SELECT vehicle_id, event_type, description, payload, occurred_at
FROM   fleet_events_raw
WHERE  severity = 'medium';

CREATE MATERIALIZED VIEW low_severity_alerts AS
SELECT vehicle_id, event_type, description, payload, occurred_at
FROM   fleet_events_raw
WHERE  severity = 'low';

-- ─── 3. Real-time speed readings ─────────────────────────────────────────────
CREATE MATERIALIZED VIEW vehicle_speeds AS
SELECT vehicle_id, speed AS speed_mph, latitude, longitude, recorded_at, solace_topic
FROM   fleet_telemetry_raw;

-- ─── 4. 5-minute tumbling window — speed averages per vehicle ────────────────
CREATE MATERIALIZED VIEW vehicle_speed_5min_avg AS
SELECT
    vehicle_id,
    window_start,
    window_end,
    AVG(speed)  AS avg_speed_mph,
    MAX(speed)  AS max_speed_mph,
    MIN(speed)  AS min_speed_mph,
    COUNT(*)    AS sample_count
FROM TUMBLE(fleet_telemetry_raw, recorded_at, INTERVAL '5 MINUTES')
GROUP BY vehicle_id, window_start, window_end;

-- ─── 5. Fleet-wide alert summary — rolling 1-hour window ─────────────────────
CREATE MATERIALIZED VIEW fleet_alert_summary AS
SELECT
    severity,
    COUNT(*)                   AS alert_count,
    COUNT(DISTINCT vehicle_id) AS affected_vehicles
FROM fleet_events_raw
WHERE occurred_at > NOW() - INTERVAL '1 HOUR'
GROUP BY severity;

-- ─── 6. Per-vehicle fuel levels ──────────────────────────────────────────────
CREATE MATERIALIZED VIEW vehicle_fuel_levels AS
SELECT vehicle_id, fuel_level AS fuel_pct, recorded_at
FROM   fleet_telemetry_raw;

-- ─── 7. High engine temperature alerts ───────────────────────────────────────
CREATE MATERIALIZED VIEW high_engine_temp_vehicles AS
SELECT vehicle_id, engine_temp AS engine_temp_f, recorded_at
FROM   fleet_telemetry_raw
WHERE  engine_temp > 220;

-- ─── 8. Alerts with correlated telemetry (stream-stream join) ────────────────
CREATE MATERIALIZED VIEW alerts_with_context AS
SELECT
    e.vehicle_id,
    e.event_type,
    e.severity,
    e.description,
    e.occurred_at                    AS alert_time,
    t.speed,
    t.fuel_level,
    t.engine_temp,
    t.tire_pressure,
    t.battery_voltage,
    t.recorded_at                    AS metric_time,
    e.occurred_at - t.recorded_at    AS time_before_alert
FROM fleet_events_raw    e
JOIN fleet_telemetry_raw t
    ON  e.vehicle_id = t.vehicle_id
    AND t.recorded_at BETWEEN e.occurred_at - INTERVAL '2 MINUTES'
                          AND e.occurred_at;

-- ─── 9. Geofence — vehicles in Boston metro bounding box ─────────────────────
CREATE MATERIALIZED VIEW vehicles_in_region_boston AS
SELECT vehicle_id, latitude, longitude, speed AS speed_mph, recorded_at
FROM   fleet_telemetry_raw
WHERE  latitude  BETWEEN 42.2 AND 42.5
  AND  longitude BETWEEN -71.2 AND -70.9;

-- ─── 10. Per-vehicle latest position ─────────────────────────────────────────
CREATE MATERIALIZED VIEW vehicle_last_known_position AS
SELECT vehicle_id, latitude, longitude, speed AS speed_mph, recorded_at
FROM   fleet_telemetry_raw;

-- ─── 11. 1-hour event count per vehicle ──────────────────────────────────────
CREATE MATERIALIZED VIEW vehicle_event_counts_1h AS
SELECT
    vehicle_id,
    severity,
    COUNT(*) AS event_count
FROM fleet_events_raw
WHERE occurred_at > NOW() - INTERVAL '1 HOUR'
GROUP BY vehicle_id, severity;""".rstrip()

# Analytics MVs to include in DROP list (order: dependents first)
STATIC_ANALYTICS_MV_NAMES = [
    "vehicle_event_counts_1h",
    "vehicle_last_known_position",
    "vehicles_in_region_boston",
    "alerts_with_context",
    "high_engine_temp_vehicles",
    "vehicle_fuel_levels",
    "fleet_alert_summary",
    "vehicle_speed_5min_avg",
    "vehicle_speeds",
    "low_severity_alerts",
    "medium_severity_alerts",
    "high_severity_alerts",
]
BRANCH_MV_NAMES = ["fleet_telemetry_raw", "fleet_events_raw", "fleet_commands_raw"]

# Columns available in each routing MV (used to filter EP-generated MV SELECTs)
ROUTING_MV_COLUMNS: dict[str, set] = {
    "fleet_telemetry_raw": {
        "vehicle_id",
        "speed", "fuel_level", "engine_temp", "tire_pressure", "battery_voltage",
        "latitude", "longitude", "recorded_at", "solace_topic",
    },
    "fleet_events_raw": {
        "vehicle_id", "event_type", "severity", "description",
        "payload", "occurred_at", "solace_topic",
    },
    "fleet_commands_raw": {
        "vehicle_id", "command_type", "parameters",
        "issued_at", "issued_by", "solace_topic",
    },
}


def _routing_mv_for_like_pattern(like_pat: str) -> str:
    """Return the routing MV that covers the given LIKE pattern."""
    if "telemetry" in like_pat:
        return "fleet_telemetry_raw"
    if "events" in like_pat:
        return "fleet_events_raw"
    if "commands" in like_pat:
        return "fleet_commands_raw"
    return "fleet_telemetry_raw"  # safe fallback


# ─── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate config/risingwave/init.sql from Solace Event Portal"
    )
    parser.add_argument("--domain", default="Fleet Operations",
                        help="Event Portal application domain name (default: 'Fleet Operations')")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated SQL to stdout instead of writing the file")
    parser.add_argument("--skip-ep", action="store_true",
                        help="Generate init.sql and registry from static schema only (no EP token required)")
    args = parser.parse_args()

    load_env(SCRIPT_DIR / ".env")

    # ── Skip-EP mode: write static-only init.sql and registry ─────────────────
    if args.skip_ep:
        print("WARNING: --skip-ep mode — generating init.sql without Event Portal catalog.", flush=True)
        print("WARNING: EP-generated MVs will not be included. Set SOLACE_CLOUD_TOKEN and re-run for full schema.", flush=True)

        # Build DROP section for static objects only (no EP-generated MV names)
        drop_lines: list[str] = []
        for n in STATIC_ANALYTICS_MV_NAMES:
            drop_lines.append(f"DROP MATERIALIZED VIEW IF EXISTS {n:<36} CASCADE;")
        for n in BRANCH_MV_NAMES:
            drop_lines.append(f"DROP MATERIALIZED VIEW IF EXISTS {n:<36} CASCADE;")
        drop_lines += [
            "DROP SOURCE IF EXISTS fleet_ingest_telemetry     CASCADE;",
            "DROP SOURCE IF EXISTS fleet_ingest_events        CASCADE;",
            "DROP SOURCE IF EXISTS fleet_ingest_commands      CASCADE;",
        ]
        drop_section = (
            "-- ── Tear down previous objects (safe to re-run) "
            "──────────────────────────────\n"
            + "\n".join(drop_lines)
        )
        ep_section = (
            "-- =========================================================================\n"
            "-- EP-GENERATED MATERIALIZED VIEWS — skipped (--skip-ep or EP unavailable)\n"
            "-- Re-run without --skip-ep to include Event Portal catalog objects.\n"
            "-- =========================================================================\n"
        )
        sql = "\n\n\n".join([
            STATIC_HEADER,
            drop_section,
            STATIC_SOURCE,
            STATIC_BRANCH_MVS,
            ep_section,
            STATIC_ANALYTICS_MVS,
        ]) + "\n"

        if args.dry_run:
            print(sql)
        else:
            out_path = SCRIPT_DIR / "config" / "risingwave" / "init.sql"
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(sql)
            print(f"Wrote {out_path}  (static schema — no EP-generated views)")

        reg_path = SCRIPT_DIR / "config" / "topic-mv-registry.yaml"
        write_registry(reg_path, STATIC_REGISTRY_MAPPINGS)
        print(f"Wrote {reg_path}  (static mappings only — no EP-generated entries)")
        return

    token = os.environ.get("SOLACE_CLOUD_TOKEN", "")
    if not token:
        sys.exit("ERROR: SOLACE_CLOUD_TOKEN not set — add it to .env or export it\n"
                 "       To generate the registry without EP: python3 generate_mvs.py --skip-ep")

    print(f"Querying Event Portal domain: {args.domain!r} ...")

    domain_id = get_domain_id(token, args.domain)
    print(f"  domain_id = {domain_id}")

    events = get_all_pages(token, "/events", {"applicationDomainId": domain_id})
    print(f"  {len(events)} events found")

    event_ids = [e["id"] for e in events]
    if not event_ids:
        sys.exit("ERROR: No events found in domain")

    event_versions = get_all_pages(token, "/eventVersions", {
        "eventIds": ",".join(event_ids),
    })
    print(f"  {len(event_versions)} event versions found")

    event_name_map = {e["id"]: e["name"] for e in events}

    # Collect unique schema version IDs and fetch their content
    schema_version_ids = list({
        evv["schemaVersionId"]
        for evv in event_versions
        if evv.get("schemaVersionId")
    })
    print(f"  {len(schema_version_ids)} schema versions referenced")

    schema_content_map: dict[str, str] = {}
    for sv_id in schema_version_ids:
        sv = ep_get(token, f"/schemaVersions/{sv_id}")
        schema_content_map[sv_id] = sv.get("data", {}).get("content", "")

    # ── Build EP-generated MV section ─────────────────────────────────────────
    ep_mv_names: list[str] = []
    ep_mv_blocks: list[str] = []

    for evv in sorted(event_versions, key=lambda x: event_name_map.get(x["eventId"], "")):
        ev_name = event_name_map.get(evv["eventId"], evv["eventId"])
        name = mv_name(ev_name)
        ep_mv_names.append(name)

        # Topic LIKE pattern from delivery descriptor
        dd = evv.get("deliveryDescriptor") or {}
        levels = (dd.get("address") or {}).get("addressLevels") or []
        like_pat = address_levels_to_like(levels) if levels else "%"

        # Route through the appropriate typed routing MV
        routing_mv = _routing_mv_for_like_pattern(like_pat)
        mv_col_set = ROUTING_MV_COLUMNS.get(routing_mv, SOURCE_COLUMNS)

        # SELECT column list: schema properties intersected with routing MV columns
        sv_id = evv.get("schemaVersionId", "")
        content_str = schema_content_map.get(sv_id, "")
        cols = [c for c in schema_columns(content_str) if c in mv_col_set]
        if not cols:
            cols = ["vehicle_id", "solace_topic"]
        col_list = ",\n       ".join(cols)

        desc = (evv.get("description") or ev_name).split("\n")[0]  # first line only
        version = evv.get("version", "")

        block = (
            f"-- {ev_name} v{version} — {desc}\n"
            f"CREATE MATERIALIZED VIEW {name} AS\n"
            f"SELECT {col_list}\n"
            f"FROM   {routing_mv}\n"
            f"WHERE  solace_topic LIKE '{like_pat}';\n"
        )
        ep_mv_blocks.append(block)

    # ── Build DROP section ─────────────────────────────────────────────────────
    drop_lines: list[str] = []
    for n in STATIC_ANALYTICS_MV_NAMES:
        drop_lines.append(f"DROP MATERIALIZED VIEW IF EXISTS {n:<36} CASCADE;")
    for n in sorted(ep_mv_names):
        drop_lines.append(f"DROP MATERIALIZED VIEW IF EXISTS {n:<36} CASCADE;")
    for n in BRANCH_MV_NAMES:
        drop_lines.append(f"DROP MATERIALIZED VIEW IF EXISTS {n:<36} CASCADE;")
    drop_lines += [
        "DROP SOURCE IF EXISTS fleet_ingest_telemetry     CASCADE;",
        "DROP SOURCE IF EXISTS fleet_ingest_events        CASCADE;",
        "DROP SOURCE IF EXISTS fleet_ingest_commands      CASCADE;",
    ]

    drop_section = (
        "-- ── Tear down previous objects (safe to re-run) "
        "──────────────────────────────\n"
        + "\n".join(drop_lines)
    )

    ep_section = (
        "-- =========================================================================\n"
        "-- EP-GENERATED MATERIALIZED VIEWS\n"
        "-- Source: Solace Event Portal — Fleet Operations domain\n"
        "-- Each view = one event version = one virtual topic subscription\n"
        "-- =========================================================================\n\n"
        + "\n".join(ep_mv_blocks)
    )

    sql = "\n\n\n".join([
        STATIC_HEADER,
        drop_section,
        STATIC_SOURCE,
        STATIC_BRANCH_MVS,
        ep_section,
        STATIC_ANALYTICS_MVS,
    ]) + "\n"

    if args.dry_run:
        print(sql)
        return

    out_path = SCRIPT_DIR / "config" / "risingwave" / "init.sql"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sql)
    print(f"\nWrote {out_path}")
    print(f"  {len(ep_mv_names)} EP-generated MVs:")
    for n in ep_mv_names:
        print(f"    {n}")

    # ── Write topic-mv-registry.yaml ──────────────────────────────────────────
    # Combine static mappings with EP-generated entries.
    ep_registry_entries = []
    for evv in sorted(event_versions, key=lambda x: event_name_map.get(x["eventId"], "")):
        ev_name = event_name_map.get(evv["eventId"], evv["eventId"])
        name = mv_name(ev_name)
        dd = evv.get("deliveryDescriptor") or {}
        levels = (dd.get("address") or {}).get("addressLevels") or []
        like_pat = address_levels_to_like(levels) if levels else "%"
        # Convert LIKE pattern (with %) back to Solace wildcard pattern (with *)
        solace_pattern = like_pat.replace("%", "*")
        ep_registry_entries.append({
            "pattern": solace_pattern,
            "mv": name,
            "time_column": _infer_time_column(like_pat),
        })

    all_mappings = STATIC_REGISTRY_MAPPINGS + ep_registry_entries
    reg_path = SCRIPT_DIR / "config" / "topic-mv-registry.yaml"
    write_registry(reg_path, all_mappings)
    print(f"\nWrote {reg_path}")
    print("\nNext: psql -h localhost -p 4566 -U root -d dev -f config/risingwave/init.sql")


if __name__ == "__main__":
    main()
