#!/usr/bin/env python3
"""
solace+ — Solace CLI extended with historical data via RisingWave.

Uses the topic-mv-registry.yaml (generated by generate_mvs.py) to map
Solace topic patterns to RisingWave materialized views, enabling transparent
historical queries and live subscriptions from a single command.

Commands:
  query     <pattern>              Pure RisingWave query — no live subscription
  subscribe <pattern> [--since]    Replay history then stream live via Solace SMF
  topic     info / lag / list      Registry inspection and data freshness
  alert     list / history / watch Alert shortcuts

Examples:
  python3 cli/solace_plus.py query "fleet/events/*/alerts/high" --since 1h
  python3 cli/solace_plus.py subscribe "fleet/events/*/alerts/high" --since 30min
  python3 cli/solace_plus.py topic lag "fleet/telemetry/*/metrics/speed"
  python3 cli/solace_plus.py alert watch --severity high
"""

import json
import os
import queue
import re
import sys
import threading
from pathlib import Path
from typing import Optional

import click
import psycopg2
import psycopg2.extras
import yaml
from dotenv import load_dotenv
from tabulate import tabulate

# ── Paths & env ──────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
REGISTRY_PATH = PROJECT_ROOT / "config" / "topic-mv-registry.yaml"

load_dotenv(PROJECT_ROOT / ".env")


# ── Config helpers ────────────────────────────────────────────────────────────

def _expand_env(text: str) -> str:
    """Expand ${VAR:-default} patterns using os.environ."""
    def _replace(m: re.Match) -> str:
        var, _, default = m.group(1).partition(":-")
        return os.environ.get(var, default)
    return re.sub(r"\$\{([^}]+)\}", _replace, text)


def load_registry() -> dict:
    """Load and return topic-mv-registry.yaml, expanding env-var placeholders."""
    if not REGISTRY_PATH.exists():
        click.echo(
            f"ERROR: Registry not found at {REGISTRY_PATH}\n"
            "Run 'python3 generate_mvs.py --skip-ep' to generate it (no EP token needed).\n"
            "Or run 'python3 generate_mvs.py' if SOLACE_CLOUD_TOKEN is set.",
            err=True,
        )
        sys.exit(1)
    text = _expand_env(REGISTRY_PATH.read_text())
    return yaml.safe_load(text)


_registry: Optional[dict] = None
_rw_conn = None


def get_registry() -> dict:
    global _registry
    if _registry is None:
        _registry = load_registry()
    return _registry


def get_rw_conn():
    global _rw_conn
    if _rw_conn is None or _rw_conn.closed:
        rw = get_registry()["risingwave"]
        _rw_conn = psycopg2.connect(
            host=rw["host"],
            port=int(rw.get("port", 4566)),
            dbname=rw.get("database", "dev"),
            user=rw.get("user", "root"),
            password=rw.get("password", ""),
        )
        _rw_conn.autocommit = True
    return _rw_conn


def get_solace_config() -> dict:
    return get_registry()["solace"]


# ── Pattern matching ──────────────────────────────────────────────────────────

def _pat_to_regex(pattern: str) -> re.Pattern:
    """Convert a Solace topic pattern (with * and >) to a regex."""
    parts = re.escape(pattern).replace(r"\*", "[^/]+").replace(r"\>", ".+")
    return re.compile(f"^{parts}$")


def find_entry(pattern: str) -> Optional[dict]:
    """Return the best registry entry for *pattern* (exact match preferred)."""
    mappings = get_registry().get("mappings", [])

    # 1. Exact match
    for m in mappings:
        if m["pattern"] == pattern:
            return m

    # 2. Registry wildcard pattern covers the query pattern
    for m in mappings:
        if _pat_to_regex(m["pattern"]).match(pattern):
            return m

    # 3. Query pattern (wildcard) covers the registry pattern
    if "*" in pattern or ">" in pattern:
        query_re = _pat_to_regex(pattern)
        for m in mappings:
            if query_re.match(m["pattern"]):
                return m

    return None


# ── Duration helpers ──────────────────────────────────────────────────────────

_DURATION_RE = re.compile(r"^(\d+)(d|h|hr|min|m|s)$", re.IGNORECASE)
_UNIT_MAP = {
    "d": "days", "h": "hours", "hr": "hours",
    "min": "minutes", "m": "minutes", "s": "seconds",
}


def duration_to_pg(s: str) -> str:
    """Convert a duration string (1h, 30min, 2d) to a PostgreSQL interval string."""
    m = _DURATION_RE.match(s.strip())
    if not m:
        raise click.BadParameter(
            f"Invalid duration '{s}' — use e.g. 1h, 30min, 2d, 10s"
        )
    n, unit = m.group(1), _UNIT_MAP[m.group(2).lower()]
    return f"{n} {unit}"


# ── Output helpers ────────────────────────────────────────────────────────────

def _serialize(v):
    """Make a value JSON-serializable."""
    if hasattr(v, "isoformat"):
        return v.isoformat()
    return v


def format_and_print(rows_raw: list, fmt: str) -> None:
    """Print a list of RealDictRow objects in the requested format."""
    if not rows_raw:
        click.echo("(no rows)")
        return
    headers = list(rows_raw[0].keys())
    if fmt == "json":
        for r in rows_raw:
            click.echo(json.dumps({k: _serialize(v) for k, v in r.items()}))
    elif fmt == "csv":
        click.echo(",".join(headers))
        for r in rows_raw:
            click.echo(",".join(str(_serialize(v)) for v in r.values()))
    else:
        rows = [list(r.values()) for r in rows_raw]
        click.echo(tabulate(rows, headers=headers, tablefmt="simple"))


def emit_event(event: dict, fmt: str) -> None:
    """Emit a single event dict (subscribe / alert watch output)."""
    if fmt == "json":
        click.echo(json.dumps({k: _serialize(v) for k, v in event.items()}))
    else:
        ts = _serialize(event.get("event_time", ""))
        source = event.get("source", "")
        topic = event.get("topic", "")
        payload = event.get("payload", {})
        vid = payload.get("vehicle_id", "")
        summary = "  ".join(
            f"{k}={_serialize(v)}"
            for k, v in payload.items()
            if k not in ("solace_topic", "vehicle_id") and v is not None
        )
        click.echo(f"[{source:7}] {ts}  {topic}  vehicle={vid}  {summary}")


# ── Solace SMF subscriber ─────────────────────────────────────────────────────

def start_smf_receiver(pattern: str, msg_queue: queue.Queue) -> threading.Event:
    """
    Connect to Solace via SMF, subscribe to *pattern*, and put received
    messages onto *msg_queue* as dicts:
        {"topic": str, "payload": dict, "source": "live"}

    Returns a threading.Event; set it to stop the receiver thread.
    """
    from solace.messaging.messaging_service import MessagingService
    from solace.messaging.resources.topic_subscription import TopicSubscription
    from solace.messaging.errors.pubsubplus_client_error import PubSubPlusClientError

    cfg = get_solace_config()
    broker_props = {
        "solace.messaging.transport.host":
            cfg["smf_host"],
        "solace.messaging.service.vpn-name":
            cfg["vpn"],
        "solace.messaging.authentication.scheme.basic.username":
            cfg["username"],
        "solace.messaging.authentication.scheme.basic.password":
            cfg["password"],
    }

    stop_event = threading.Event()

    def _run():
        try:
            svc = MessagingService.builder().from_properties(broker_props).build()
            svc.connect()
            receiver = (
                svc.create_direct_message_receiver_builder()
                .with_subscriptions([TopicSubscription.of(pattern)])
                .build()
            )
            receiver.start()
            while not stop_event.is_set():
                msg = receiver.receive_message(timeout=200)  # ms
                if msg is None:
                    continue
                topic = msg.get_destination_name()
                raw = msg.get_payload_as_bytes()
                try:
                    payload = json.loads(raw.decode("utf-8")) if raw else {}
                except (json.JSONDecodeError, UnicodeDecodeError):
                    payload = {"raw": str(raw)}
                msg_queue.put({"topic": topic, "payload": payload, "source": "live"})
            receiver.terminate()
            svc.disconnect()
        except PubSubPlusClientError as exc:
            click.echo(f"[smf] connection error: {exc}", err=True)
        except Exception as exc:  # noqa: BLE001
            click.echo(f"[smf] unexpected error: {exc}", err=True)

    t = threading.Thread(target=_run, daemon=True, name="smf-receiver")
    t.start()
    return stop_event


# ── Dedup / topic reconstruction helpers ─────────────────────────────────────

def _dedup_key(row_or_payload: dict, time_col: str) -> tuple:
    """(vehicle_id, timestamp_string) — unique per event."""
    vid = row_or_payload.get("vehicle_id", "")
    ts = row_or_payload.get(
        time_col,
        row_or_payload.get("recorded_at",
        row_or_payload.get("occurred_at",
        row_or_payload.get("issued_at", ""))),
    )
    return (vid, str(ts))


def _time_col_from_payload(payload: dict) -> str:
    """Guess the timestamp field name from a live message payload."""
    for col in ("recorded_at", "occurred_at", "issued_at"):
        if col in payload:
            return col
    return "recorded_at"


def reconstruct_topic(pattern: str, row: dict) -> str:
    """
    Build a topic string from a registry pattern + MV row data.
    Uses row["solace_topic"] if present; otherwise fills wildcards from row fields.
    """
    if row.get("solace_topic"):
        return row["solace_topic"]
    topic = pattern
    vid = row.get("vehicle_id", "unknown")
    topic = topic.replace("*", vid, 1)
    if "*" in topic:
        filler = (
            row.get("severity")
            or row.get("metric_type")
            or row.get("command_type")
            or "unknown"
        )
        topic = topic.replace("*", filler, 1)
    return topic


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

@click.group()
def cli():
    """solace+ — Solace CLI extended with historical data via RisingWave."""


# ── query ─────────────────────────────────────────────────────────────────────

@cli.command()
@click.argument("pattern", required=False)
@click.option("--window", default=None, metavar="DURATION",
              help="Use windowed aggregation MV (e.g. 5min).")
@click.option("--enrich", default=None, metavar="TYPE",
              help="Use enriched join MV (e.g. context).")
@click.option("--region", default=None, metavar="NAME",
              help="Use spatial filter MV (e.g. boston).")
@click.option("--sql", "raw_sql", default=None, metavar="SQL",
              help="Execute raw SQL directly against RisingWave.")
@click.option("--since", default=None, metavar="DURATION",
              help="Restrict to rows newer than this (1h, 30min, 2d).")
@click.option("--limit", default=20, show_default=True,
              help="Maximum rows to return.")
@click.option("--format", "fmt",
              type=click.Choice(["table", "json", "csv"]),
              default="table", show_default=True)
def query(pattern, window, enrich, region, raw_sql, since, limit, fmt):
    """Query historical data from RisingWave using a Solace topic PATTERN.

    \b
    Examples:
      solace+ query "fleet/events/*/alerts/high" --since 1h
      solace+ query "fleet/telemetry/*/metrics/speed" --window 5min
      solace+ query "fleet/events/*/alerts/high" --enrich context
      solace+ query "fleet/telemetry/*/metrics/location" --region boston
      solace+ query --sql "SELECT COUNT(*) FROM high_severity_alerts"
    """
    conn = get_rw_conn()
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    # Raw SQL bypass
    if raw_sql:
        cur.execute(raw_sql)
        format_and_print(cur.fetchall(), fmt)
        return

    if not pattern:
        raise click.UsageError("PATTERN is required unless --sql is used.")

    entry = find_entry(pattern)
    if not entry:
        click.echo(
            f"ERROR: No MV mapping found for '{pattern}'.\n"
            "Run 'solace+ topic list --backed' to see supported patterns, "
            "or use --sql for a raw query.",
            err=True,
        )
        sys.exit(1)

    # Choose the target MV
    time_col = entry.get("time_column")

    if window:
        agg_key = f"window_{window.replace(' ', '').replace('min', 'min')}"
        agg_map = entry.get("aggregates") or {}
        mv = agg_map.get(agg_key) or next(iter(agg_map.values()), None)
        if not mv:
            click.echo(
                f"ERROR: No windowed aggregation MV for '{pattern}'.\n"
                f"Available: {agg_map}",
                err=True,
            )
            sys.exit(1)
        time_col = None  # aggregates don't support --since

    elif enrich:
        mv = entry.get("enriched")
        if not mv:
            click.echo(f"ERROR: No enrichment MV for '{pattern}'.", err=True)
            sys.exit(1)
        # alerts_with_context uses alert_time
        if mv == "alerts_with_context":
            time_col = "alert_time"

    elif region:
        spatial = entry.get("spatial") or {}
        mv = spatial.get(region.lower())
        if not mv:
            click.echo(
                f"ERROR: No spatial MV for region '{region}'.\n"
                f"Available regions: {list(spatial.keys())}",
                err=True,
            )
            sys.exit(1)

    else:
        mv = entry["mv"]

    # Build and execute query
    where_parts, params = [], []
    if since and time_col:
        where_parts.append(f"{time_col} > NOW() - INTERVAL %s")
        params.append(duration_to_pg(since))

    where_sql = f"WHERE {' AND '.join(where_parts)}" if where_parts else ""
    order_sql = f"ORDER BY {time_col} DESC" if time_col else ""
    params.append(limit)

    cur.execute(f"SELECT * FROM {mv} {where_sql} {order_sql} LIMIT %s", params)
    format_and_print(cur.fetchall(), fmt)


# ── subscribe ─────────────────────────────────────────────────────────────────

@cli.command()
@click.argument("pattern")
@click.option("--since", default=None, metavar="DURATION",
              help="Replay historical events first, then stream live (e.g. 1h, 30min).")
@click.option("--format", "fmt",
              type=click.Choice(["json", "line"]),
              default="json", show_default=True,
              help="json = JSON Lines per event; line = compact human-readable.")
def subscribe(pattern, since, fmt):
    """Subscribe to a Solace topic PATTERN via SMF.

    With --since: historical events are replayed from RisingWave (as individual
    Solace-style events), then the buffer of live SMF messages captured during
    the replay drains oldest-first, and the stream continues live.

    Without --since: streams live events only.  Press Ctrl-C to stop.

    \b
    Examples:
      solace+ subscribe "fleet/events/*/alerts/high" --since 1h
      solace+ subscribe "fleet/telemetry/vehicle_005/metrics/speed" --since 30min
      solace+ subscribe "fleet/>"
    """
    entry = find_entry(pattern) if since else None
    msg_queue: queue.Queue = queue.Queue()

    # Start SMF receiver immediately so no live messages are lost during replay
    stop_event = start_smf_receiver(pattern, msg_queue)
    seen: set = set()

    try:
        if since and entry:
            mv = entry["mv"]
            time_col = entry.get("time_column")
            if not time_col:
                click.echo(
                    f"WARN: '{pattern}' maps to aggregate MV '{mv}' with no time "
                    "column — skipping history replay, streaming live only.",
                    err=True,
                )
            else:
                conn = get_rw_conn()
                cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
                cur.execute(
                    f"SELECT * FROM {mv} "
                    f"WHERE {time_col} > NOW() - INTERVAL %s "
                    f"ORDER BY {time_col} ASC",
                    (duration_to_pg(since),),
                )
                for row in cur:
                    row_dict = dict(row)
                    key = _dedup_key(row_dict, time_col)
                    seen.add(key)
                    emit_event(
                        {
                            "source": "history",
                            "topic": reconstruct_topic(pattern, row_dict),
                            "event_time": row_dict.get(time_col, ""),
                            "payload": row_dict,
                        },
                        fmt,
                    )

                # Drain queued live messages, deduplicating against history
                while not msg_queue.empty():
                    live = msg_queue.get_nowait()
                    key = _dedup_key(live["payload"], time_col)
                    if key not in seen:
                        seen.add(key)
                        ts = live["payload"].get(time_col, "")
                        emit_event(
                            {
                                "source": "live",
                                "topic": live["topic"],
                                "event_time": ts,
                                "payload": live["payload"],
                            },
                            fmt,
                        )

        # Stream live indefinitely
        while True:
            try:
                live = msg_queue.get(timeout=0.2)
                tc = _time_col_from_payload(live["payload"])
                emit_event(
                    {
                        "source": "live",
                        "topic": live["topic"],
                        "event_time": live["payload"].get(tc, ""),
                        "payload": live["payload"],
                    },
                    fmt,
                )
            except queue.Empty:
                pass

    except KeyboardInterrupt:
        click.echo("\n[stopped]", err=True)
    finally:
        stop_event.set()


# ── topic ─────────────────────────────────────────────────────────────────────

@cli.group()
def topic():
    """Inspect the topic-to-MV registry and measure RisingWave data freshness."""


@topic.command("info")
@click.argument("pattern")
def topic_info(pattern):
    """Show the registry entry for PATTERN."""
    entry = find_entry(pattern)
    if not entry:
        click.echo(f"No registry entry for: {pattern}", err=True)
        sys.exit(1)
    click.echo(f"Pattern    : {entry['pattern']}")
    click.echo(f"MV         : {entry['mv']}")
    click.echo(f"Time col   : {entry.get('time_column', '—')}")
    if entry.get("aggregates"):
        for k, v in entry["aggregates"].items():
            click.echo(f"Aggregate  : --window {k.replace('window_', '')} → {v}")
    if entry.get("enriched"):
        click.echo(f"Enriched   : --enrich context → {entry['enriched']}")
    if entry.get("spatial"):
        for k, v in entry["spatial"].items():
            click.echo(f"Spatial    : --region {k} → {v}")


@topic.command("lag")
@click.argument("pattern")
def topic_lag(pattern):
    """Show how stale the RisingWave MV is for PATTERN (vs. current time)."""
    entry = find_entry(pattern)
    if not entry:
        click.echo(f"No registry entry for: {pattern}", err=True)
        sys.exit(1)
    mv = entry["mv"]
    time_col = entry.get("time_column")
    if not time_col:
        click.echo(
            f"'{mv}' is an aggregate with no direct time column — lag not measurable."
        )
        return
    conn = get_rw_conn()
    cur = conn.cursor()
    cur.execute(
        f"SELECT NOW() - MAX({time_col}) AS lag, MAX({time_col}) AS latest FROM {mv}"
    )
    lag, latest = cur.fetchone()
    if lag is None:
        click.echo(f"{mv}: no data yet")
    else:
        secs = int(lag.total_seconds())
        click.echo(f"MV={mv}  lag={secs}s  latest={latest}")


@topic.command("list")
@click.option("--backed", is_flag=True,
              help="Only show patterns that have a RisingWave MV backing.")
def topic_list(backed):
    """List all topic patterns and their backing RisingWave MVs."""
    mappings = get_registry().get("mappings", [])
    rows = []
    for m in mappings:
        if backed and not m.get("mv"):
            continue
        extras = []
        for k, v in (m.get("aggregates") or {}).items():
            extras.append(f"window_{k.replace('window_','')}→{v}")
        if m.get("enriched"):
            extras.append(f"enrich→{m['enriched']}")
        for k, v in (m.get("spatial") or {}).items():
            extras.append(f"{k}→{v}")
        rows.append([
            m["pattern"],
            m.get("mv", "—"),
            m.get("time_column", "—"),
            "  ".join(extras) or "—",
        ])
    click.echo(
        tabulate(rows, headers=["Pattern", "MV", "Time col", "Extras"],
                 tablefmt="simple")
    )


# ── alert ─────────────────────────────────────────────────────────────────────

@cli.group()
def alert():
    """Shorthand commands for fleet alert queries and live monitoring."""


@alert.command("list")
@click.option("--severity", type=click.Choice(["high", "medium", "low"]),
              default="high", show_default=True)
@click.option("--limit", default=20, show_default=True)
@click.option("--format", "fmt",
              type=click.Choice(["table", "json", "csv"]),
              default="table", show_default=True)
def alert_list(severity, limit, fmt):
    """Show the most recent alerts at the specified severity."""
    mv_map = {
        "high": ("high_severity_alerts", "occurred_at"),
        "medium": ("medium_severity_alerts", "occurred_at"),
        "low": ("low_severity_alerts", "occurred_at"),
    }
    mv, time_col = mv_map[severity]
    conn = get_rw_conn()
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    cur.execute(
        f"SELECT * FROM {mv} ORDER BY {time_col} DESC LIMIT %s",
        (limit,),
    )
    format_and_print(cur.fetchall(), fmt)


@alert.command("history")
@click.option("--since", default="4h", show_default=True, metavar="DURATION")
@click.option("--severity",
              type=click.Choice(["high", "medium", "low", "all"]),
              default="all", show_default=True)
@click.option("--enrich", is_flag=True,
              help="Include correlated telemetry (alerts_with_context MV).")
@click.option("--format", "fmt",
              type=click.Choice(["table", "json", "csv"]),
              default="table", show_default=True)
def alert_history(since, severity, enrich, fmt):
    """Show alert history for the past SINCE duration."""
    conn = get_rw_conn()
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    pg_interval = duration_to_pg(since)

    if enrich:
        sev_filter = f" AND e.severity = '{severity}'" if severity != "all" else ""
        cur.execute(
            "SELECT * FROM alerts_with_context "
            f"WHERE alert_time > NOW() - INTERVAL %s{sev_filter} "
            "ORDER BY alert_time DESC LIMIT 50",
            (pg_interval,),
        )
    elif severity == "all":
        cur.execute(
            "SELECT * FROM fleet_events_raw "
            "WHERE occurred_at > NOW() - INTERVAL %s "
            "ORDER BY occurred_at DESC LIMIT 50",
            (pg_interval,),
        )
    else:
        mv_map = {
            "high": "high_severity_alerts",
            "medium": "medium_severity_alerts",
            "low": "low_severity_alerts",
        }
        mv = mv_map[severity]
        cur.execute(
            f"SELECT * FROM {mv} "
            "WHERE occurred_at > NOW() - INTERVAL %s "
            "ORDER BY occurred_at DESC LIMIT 50",
            (pg_interval,),
        )

    format_and_print(cur.fetchall(), fmt)


@alert.command("watch")
@click.option("--severity",
              type=click.Choice(["high", "medium", "low", "all"]),
              default="high", show_default=True,
              help="Client-side severity filter applied to the live stream.")
@click.option("--format", "fmt",
              type=click.Choice(["json", "line"]),
              default="json", show_default=True)
def alert_watch(severity, fmt):
    """Stream live alerts from Solace via SMF. Press Ctrl-C to stop."""
    msg_queue: queue.Queue = queue.Queue()
    stop_event = start_smf_receiver("fleet/events/>", msg_queue)
    click.echo(
        f"[watching] fleet/events/>  severity={severity}  Ctrl-C to stop",
        err=True,
    )
    try:
        while True:
            try:
                live = msg_queue.get(timeout=0.2)
                payload = live["payload"]
                if severity != "all" and payload.get("severity") != severity:
                    continue
                emit_event(
                    {
                        "source": "live",
                        "topic": live["topic"],
                        "event_time": payload.get("occurred_at", ""),
                        "payload": payload,
                    },
                    fmt,
                )
            except queue.Empty:
                pass
    except KeyboardInterrupt:
        click.echo("\n[stopped]", err=True)
    finally:
        stop_event.set()


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    cli()
